name: Build Windows GUI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg.exe install `
            cgal:x64-windows `
            boost:x64-windows `
            eigen3:x64-windows `
            cli11:x64-windows `
            glfw3[core]:x64-windows-static `
            opengl:x64-windows `
            imgui:x64-windows `
            suitesparse:x64-windows
          .\vcpkg\vcpkg.exe integrate install

      - name: Clean build directory
        run: |
          if (Test-Path -Path "build") { Remove-Item -Recurse -Force build }

      - name: Configure CMake
        run: cmake -S . -B build `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows-static `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}/vcpkg/installed/x64-windows-static/share
          -DCMAKE_BUILD_TYPE=Release `
          -DSHRINK_MORPH_USE_SUITESPARSE=OFF `
          -DSHRINK_MORPH_USE_MKL=OFF

      - name: Build
        run: cmake --build build --config Release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: shrink-morph-windows
          path: |
            build/Release/*.exe
            build/Release/*.dll
